import { useUserContext } from "../../context/UserContext.jsx";
import { Navigate, useLocation } from "react-router-dom";
import Loading from "../../components/Loading.jsx";

 const OnboardingGuard = ({ children }) => {
  const { dbUser, loading } = useUserContext();
  const location = useLocation();
// console.log("inside OnboardingGuard");

  if (loading) return <Loading />;

  //if backend is down to avoid loop generated by this gurd which says if dbuser is not there go to / and on / when guest gurd checks that there is user go to /dashboard which is again this guard so this creates a loop 
  if (dbUser?.isServerError) {
    console.log("inside onboardguard");
    
    return (
      <div className="flex flex-col items-center justify-center h-screen">
        <h1>Server is currently unreachable</h1>
        <p>Please check your connection or try again later.</p>
        <button onClick={() => window.location.reload()} className="mt-4 p-2 bg-blue-500 text-white">
          Retry
        </button>
      </div>
    );
  }
  // If the user has NO profile in the DB
  if(dbUser===null){
    return <Navigate to="/" replace />
  }
  if (dbUser?.isNew) {
    if (location.pathname !== "/complete-profile") {
      return <Navigate to="/complete-profile" replace />;
    }
  } 
  
  // If the user HAS a profile but is trying to go to /complete-profile
  if (!dbUser?.isNew && location.pathname === "/complete-profile") {
    return <Navigate to="/dashboard" replace />;
  }
//YAHA PE GEMINI SE CODE LENA FOR NOT FURTHERING THE PROCESS OF APP 
  return children;
};

export default OnboardingGuard