import { useUserContext } from "../../context/UserContext.jsx";
import { Navigate, useLocation } from "react-router-dom";
import Loading from "../../components/Loading.jsx";

 const OnboardingGuard = ({ children }) => {
  const { dbUser, loading, isError } = useUserContext();
  const location = useLocation();
// console.log("inside OnboardingGuard");

  if (loading) return <Loading />;

  //if backend is down to avoid loop generated by this gurd which says if dbuser is not there go to / and on / when guest gurd checks that there is user go to /dashboard which is again this guard so this creates a loop 
  if (isError) {
    console.log("inside onboardguard");
    
    return (
  <div className="flex flex-col items-center justify-center h-screen text-center">
        <h1 className="text-xl font-bold text-red-600">Server Offline</h1>
        <p>We can't connect to our services right now.</p>
        <button 
          onClick={() => window.location.reload()} 
          className="mt-4 p-2 bg-blue-500 text-white rounded"
        >
          Try Again
        </button>
      </div>
    );
  }
 //if no user data at all (not logged in)
  if (!dbUser) {
    return <Navigate to="/" replace />;
  }

  // onboarding logic
  if (dbUser.isNew) {
    if (location.pathname !== "/complete-profile") {
      return <Navigate to="/complete-profile" replace />;
    }
  } else {
    // If they is not new but are trying to access complete-profile
    if (location.pathname === "/complete-profile") {
      return <Navigate to="/dashboard" replace />;
    }
  }
  return children;
};

export default OnboardingGuard